-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 10:30:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_shoeverse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_shoeverse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_shoeverse` DEFAULT CHARACTER SET utf8 ;
USE `db_shoeverse` ;

-- -----------------------------------------------------
-- Table `db_shoeverse`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `lname` VARCHAR(100) NOT NULL,
  `fname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `contact_number` VARCHAR(13) NOT NULL,
  `address_line` VARCHAR(255) NOT NULL,
  `role` ENUM('Admin', 'Customer') NOT NULL,
  `photo` VARCHAR(255) NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shoeverse`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `date_shipped` DATE NULL,
  `shipping_fee` DECIMAL(7,2) NULL,
  `status` ENUM('Pending', 'Shipped', 'Delivered', 'Cancelled') NOT NULL,
  `payment_method` ENUM('Online','COD') NOT NULL DEFAULT 'COD',
  `shipping_address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_users_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_shoeverse`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shoeverse`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`brands` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shoeverse`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shoeverse`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `product_name` VARCHAR(100) NOT NULL,
  `size` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `date_added` DATE NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_brands1_idx` (`brand_id` ASC) ,
  INDEX `fk_products_category1_idx` (`category_id` ASC) ,
  CONSTRAINT `fk_products_brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `db_shoeverse`.`brands` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_shoeverse`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shoeverse`.`product_images`
-- Additional images per product (gallery)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`product_images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `idx_prodimg_product` (`product_id` ASC),
  CONSTRAINT `fk_prodimg_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_shoeverse`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shoeverse`.`product_variants`
-- Stock per (color + size) combination for a product
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`product_variants` (
  `variant_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `color_name` VARCHAR(100) NOT NULL,
  `color_image` VARCHAR(255) NULL,
  `size_value` VARCHAR(20) NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`variant_id`),
  UNIQUE KEY `uq_variant_product_color_size` (`product_id`,`color_name`,`size_value`),
  INDEX `idx_variant_product` (`product_id` ASC),
  CONSTRAINT `fk_variant_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_shoeverse`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shoeverse`.`orderline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`orderline` (
  `orderline_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `variant_id` INT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`orderline_id`),
  INDEX `fk_orderline_orders1_idx` (`order_id` ASC) ,
  INDEX `fk_orderline_products1_idx` (`product_id` ASC) ,
  INDEX `fk_orderline_variants_idx` (`variant_id` ASC) ,
  CONSTRAINT `fk_orderline_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_shoeverse`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderline_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_shoeverse`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderline_variants`
    FOREIGN KEY (`variant_id`)
    REFERENCES `db_shoeverse`.`product_variants` (`variant_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shoeverse`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`carts` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `variant_id` INT NULL,
  `quantity` INT NOT NULL,
  `date_added` DATE NOT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `fk_carts_users1_idx` (`user_id` ASC) ,
  INDEX `fk_carts_products1_idx` (`product_id` ASC) ,
  INDEX `fk_carts_variants_idx` (`variant_id` ASC) ,
  CONSTRAINT `fk_carts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_shoeverse`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_shoeverse`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_variants`
    FOREIGN KEY (`variant_id`)
    REFERENCES `db_shoeverse`.`product_variants` (`variant_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `db_shoeverse`.`reviews`
-- Product reviews left by customers
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shoeverse`.`reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `rating` INT NOT NULL,
  `review_text` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `idx_reviews_user` (`user_id` ASC),
  INDEX `idx_reviews_product` (`product_id` ASC),
  CONSTRAINT `fk_reviews_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_shoeverse`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reviews_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_shoeverse`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- View `db_shoeverse`.`order_transaction_details`
-- A view that exposes order header fields combined with each orderline,
-- plus computed subtotal and grand total per order.
-- -----------------------------------------------------
DROP VIEW IF EXISTS `db_shoeverse`.`order_transaction_details`;
CREATE VIEW `db_shoeverse`.`order_transaction_details` AS
SELECT
  o.order_id,
  o.user_id,
  u.fname,
  u.email,
  o.order_date,
  o.date_shipped,
  o.shipping_fee,
  o.status,
  o.payment_method,
  o.payment_info,
  o.shipping_address,
  ol.orderline_id,
  ol.product_id,
  p.product_name,
  ol.variant_id,
  pv.color_name AS variant_color,
  pv.size_value AS variant_size,
  ol.quantity,
  p.price AS unit_price,
  (ol.quantity * p.price) AS line_total,
  (
    SELECT IFNULL(SUM(ol2.quantity * p2.price),0)
    FROM db_shoeverse.orderline ol2
    JOIN db_shoeverse.products p2 ON ol2.product_id = p2.product_id
    WHERE ol2.order_id = o.order_id
  ) AS subtotal,
  (
    (
      SELECT IFNULL(SUM(ol2.quantity * p2.price),0)
      FROM db_shoeverse.orderline ol2
      JOIN db_shoeverse.products p2 ON ol2.product_id = p2.product_id
      WHERE ol2.order_id = o.order_id
    ) + IFNULL(o.shipping_fee,0)
  ) AS grand_total
FROM db_shoeverse.orders o
JOIN db_shoeverse.users u ON o.user_id = u.user_id
JOIN db_shoeverse.orderline ol ON o.order_id = ol.order_id
JOIN db_shoeverse.products p ON ol.product_id = p.product_id
LEFT JOIN db_shoeverse.product_variants pv ON ol.variant_id = pv.variant_id;
